[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
hedera_testnet = "${ARKHIA_API_URL}"

[etherscan]
hedera_testnet = { key = "", url = "${ARKHIA_API_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
