name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Format code
        run: |
          forge fmt --check
          echo "✓ Formatting check passed"

      - name: Build contracts
        run: |
          forge build
          echo "✓ Build successful"

      - name: Run tests
        run: |
          forge test
          echo "✓ All tests passed"
